name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    strategy:
      matrix:
        xcode: ['15.0']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode }}.app
      
    - name: Show Xcode version
      run: xcodebuild -version
      
    - name: Show Swift version
      run: swift --version
      
    - name: Verify Xcode installation
      run: |
        if [ ! -d "/Applications/Xcode_${{ matrix.xcode }}.app" ]; then
          echo "Error: Xcode ${{ matrix.xcode }} not found"
          ls -la /Applications/Xcode*
          exit 1
        fi
        echo "Xcode ${{ matrix.xcode }} found and selected"
      
    - name: Build RouteX
      run: |
        chmod +x ./build.sh
        ./build.sh
      timeout-minutes: 10
        
    - name: Build for release
      run: |
        xcodebuild archive -project RouteX.xcodeproj -scheme RouteX -archivePath RouteX.xcarchive -derivedDataPath build/DerivedData
      timeout-minutes: 15
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: RouteX-${{ matrix.xcode }}
        path: RouteX.xcarchive
        
 